# Generated by Django 3.1 on 2020-08-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
