# Generated by Django 3.1 on 2020-08-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0002_auto_20200812_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
