# Generated by Django 3.1 on 2020-08-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0003_auto_20200812_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='produits',
        ),
        migrations.AddField(
            model_name='produit',
            name='produits',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='achat.panier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
